import pandas as pd   
import numpy as np    
data = pd.Series([1,2,np.nan,4,5,6], index=['a','b','c','d','e','f'])
print(data.describe())
print(data.mean())
print(data.sum())
print(data.cumsum())
print(data.std())
b = data.map(lambda i : i*3)
print(b)
a = data.sort_values()
print(a)
m = data.drop('c',inplace = True)
print(m)
print(data.isnull())
print(data.notnull())
print(data.fillna(20))
print(data.dropna())
print(data.iloc[0:3])
print(data.loc['b':'c'])
print(data[data < 5])
x = data.aggregate(['sum','cumsum','std'])
print(x)
aggregated = data.aggregate(['sum', 'mean', 'std'])
print(aggregated)